using UnityEngine;

/*
Codes below are generated by ChatGPT, this mark the generated shape as clone shape.
https://chatgpt.com
The code snippet appears in its original form.
*/

public class CloneObject : MonoBehaviour
{
    private Rigidbody rb;

    private void Awake()
    {
        rb = GetComponent<Rigidbody>();
    }

    private void OnEnable()
    {
        // Subscribe to controller event
        ClonePhysicsController.OnHighlightStateChanged += HandleHighlightStateChanged;
    }

    private void OnDisable()
    {
        // Unsubscribe to prevent error
        ClonePhysicsController.OnHighlightStateChanged -= HandleHighlightStateChanged;
    }

    private void HandleHighlightStateChanged(bool isHighlighted)
    {
        if (rb != null)
        {
            rb.isKinematic = isHighlighted; // Freeze when highlights, unfreeze without highlight.
        }
    }
}

// End code snippet (Aims for clone object marking, distinguish from sample shape)