using UnityEngine;
using System; // 👈 新增，用于事件


/*
Codes below are generated by ChatGPT, this code aims to spawn the clone shape based on user's grabing action.
Compare to iteration 2, the spawn position can be bound to specific object, then spawn relative to that object.
https://chatgpt.com
The code snippet appears in its original form.
*/

[RequireComponent(typeof(Collider))]
public class CloneOnGrab : MonoBehaviour
{
    [Header("Grabbable Prefab")]
    public GameObject samplePrefab;

    [Header("Sound effect when cloning")]
    public AudioClip spawnSound;
    [Range(0f, 2f)]
    public float soundVolume = 2f;

    // 🟢 New component, editable spawn point, can be bound to specific object.
    [Header("Spawn Position Settings")]
    public Transform spawnAnchor;  // If empty, use default spawn position.
    public Vector3 spawnOffset = new Vector3(0f, 2f, 0f); // 


    private Vector3 spawnPosition = new Vector3(-0.3f, 2f, 3.8f);
    public Vector3 spawnScale = new Vector3(0.2f, 0.2f, 0.2f);

    private bool hasSpawned = false;

    // Trigger when the clone event occurred.
    public event Action<GameObject> OnCloneSpawned;

    private void OnTriggerStay(Collider other)
    {
        var interactor = other.GetComponentInParent<UnityEngine.Component>();
        if (interactor == null) return;

        bool isGrabbing =
            OVRInput.Get(OVRInput.Button.PrimaryHandTrigger, OVRInput.Controller.LTouch) ||
            OVRInput.Get(OVRInput.Button.PrimaryHandTrigger, OVRInput.Controller.RTouch);

        if (isGrabbing && !hasSpawned)
        {
            GameObject clone = SpawnClone();
            hasSpawned = true;

            // Notify external event manager
            OnCloneSpawned?.Invoke(clone);
        }
    }

    private void OnTriggerExit(Collider other)
    {
        hasSpawned = false;
    }

    private GameObject SpawnClone()
    {
        if (samplePrefab == null)
        {
            Debug.LogError("[CloneOnGrab] samplePrefab is empty！");
            return null;
        }

        // 🟢 New position logic, support panel bounding and offset setting.
        Vector3 finalSpawnPos;
        Quaternion finalSpawnRot;

        if (spawnAnchor != null)
        {
            // Use the bound logic and spawn based on the current bounding object
            finalSpawnPos = spawnAnchor.position + spawnAnchor.TransformDirection(spawnOffset);
            finalSpawnRot = spawnAnchor.rotation;
        }
        else
        {
            // Use fixed position if there's no bounding object
            finalSpawnPos = spawnPosition;
            finalSpawnRot = Quaternion.identity;
        }

        GameObject clone = Instantiate(samplePrefab, finalSpawnPos, finalSpawnRot);
        clone.transform.localScale = spawnScale;

        Rigidbody rb = clone.GetComponent<Rigidbody>();
        if (rb == null)
        {
            rb = clone.AddComponent<Rigidbody>();
        }
        rb.useGravity = true;
        rb.isKinematic = false;

        Destroy(clone.GetComponent<Rotator>());
        Destroy(clone.GetComponent<CloneOnGrab>());

        if (spawnSound != null)
        {
            AudioSource.PlayClipAtPoint(spawnSound, finalSpawnPos, soundVolume);
        }

        return clone;
    }

    private void OnDrawGizmosSelected()
    {
        Transform refPoint = spawnAnchor != null ? spawnAnchor : transform;
        Vector3 worldPos = refPoint.position + refPoint.TransformDirection(spawnOffset);

        Gizmos.color = Color.cyan;
        Gizmos.DrawWireSphere(worldPos, 0.05f);
        Gizmos.DrawLine(refPoint.position, worldPos);
    }
}

//End code snippet
