using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;
using Oculus.Interaction;
using Oculus.Interaction.HandGrab;
/*
Codes below are generated by ChatGPT, it allows shape deleting upon colliding. This Code has been through several versions, and this is the final one.
https://chatgpt.com
The code snippet appears in its original form
*/


[RequireComponent(typeof(Collider))]
[RequireComponent(typeof(AudioSource))]
public class TrashBinSafe : MonoBehaviour
{
    [Tooltip("Tag for deleted object(Fill with 'Clone' or leave it empty)")]
    public string targetTag = "Clone";

    [Tooltip("Audio effect when deleting")]
    public AudioClip trashSound;

    [Tooltip("Time in seconds after hiding the object, allows Interaction SDK to disable any references before destory")]
    public float destroyDelay = 0.2f;

    [Tooltip("If setting setActive to false after hiding.")]
    public bool deactivateImmediately = true;

    private AudioSource _audioSource;

    private void Awake()
    {
        _audioSource = GetComponent<AudioSource>();
        _audioSource.playOnAwake = false;
    }

    private void OnTriggerEnter(Collider other)
    {
        // Select the root target with rigid body to delete.
        GameObject targetRoot = other.attachedRigidbody != null ? other.attachedRigidbody.gameObject : other.transform.root.gameObject;
        if (targetRoot == null) return;

        // tag filtering
        if (!string.IsNullOrEmpty(targetTag))
        {
            if (!targetRoot.CompareTag(targetTag)) return;
        }
        else
        {
            // If there's no tag, then delete any object with rigidbody(includes camera)
            if (targetRoot.GetComponentInChildren<Rigidbody>() == null) return;
        }

        // Play sound effect
        if (trashSound != null && _audioSource != null)
        {
            _audioSource.PlayOneShot(trashSound);
        }

        // 1) Disable all the collider.
        var cols = targetRoot.GetComponentsInChildren<Collider>(true);
        foreach (var c in cols) c.enabled = false;

        // 2) Disable interaction component(grab interaction)
        var grabInteractables = targetRoot.GetComponentsInChildren<GrabInteractable>(true);
        foreach (var gi in grabInteractables)
        {
            try { gi.enabled = false; } catch { }
        }
        var grabbables = targetRoot.GetComponentsInChildren<Grabbable>(true);
        foreach (var g in grabbables)
        {
            try { g.enabled = false; } catch { }
        }
        var handGrab = targetRoot.GetComponentInChildren<HandGrabInteractable>(true);
        if (handGrab != null)
        {
            try { handGrab.enabled = false; } catch { }
        }

        // 3) Try to let the scene release the interactor
        TryForceReleaseFromAllInteractors(targetRoot);

        // 4) Hidden the delete object immediately
        if (deactivateImmediately)
        {
            targetRoot.SetActive(false);
        }

        // 5) Delay the destroy process, allows the scene to release the grabbing.
        StartCoroutine(DelayedDestroy(targetRoot, destroyDelay));
    }

    private IEnumerator DelayedDestroy(GameObject go, float delay)
    {
        
        yield return null;
        yield return null;

        // Extra reading seconds, in terms of 0.xs.
        if (delay > 0f) yield return new WaitForSeconds(delay);

        if (go != null)
        {
            try { Destroy(go); }
            catch (Exception e) { Debug.LogWarning("[TrashBinSafe] Destroy failed: " + e); }
        }
    }

    // Try to release all the summary cited by the interactor.
    private void TryForceReleaseFromAllInteractors(GameObject targetRoot)
    {
        // Acquire possible interactable compnent
        var targetGrabInteractable = targetRoot.GetComponentInChildren<GrabInteractable>(true);
        var targetGrabbable = targetRoot.GetComponentInChildren<Grabbable>(true);
        UnityEngine.Object possibleTargetComponent = (UnityEngine.Object)targetGrabInteractable ?? targetGrabbable ?? (UnityEngine.Object)targetRoot;

        
        string[] candidateMethodNames = new string[]
        {
            "ForceRelease", "ForceDeselect", "ForceSelect", "Release", "Unselect",
            "EndManualInteraction", "EndInteraction", "StopManualInteraction",
            "Deselect", "CancelSelect", "ClearSelection", "ClearSelected"
        };

        // Find all the interactables in the scene
        GrabInteractor[] allInteractors = FindObjectsOfType<GrabInteractor>(true);
        foreach (var inter in allInteractors)
        {
            Type interType = inter.GetType();

            bool didInvoke = false;

            // Invoke normal release-like function
            foreach (var mname in candidateMethodNames)
            {
                try
                {
                    MethodInfo mi = interType.GetMethod(mname, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
                    if (mi == null) continue;

                    var parms = mi.GetParameters();
                    if (parms.Length == 0)
                    {
                        
                        mi.Invoke(inter, null);
                        didInvoke = true;
                    }
                    else if (parms.Length == 1)
                    {
                        // If the parameter type matches the possible target, pass in
                        if (possibleTargetComponent != null && parms[0].ParameterType.IsAssignableFrom(possibleTargetComponent.GetType()))
                        {
                            mi.Invoke(inter, new object[] { possibleTargetComponent });
                            didInvoke = true;
                        }
                        else
                        {
                            // Also try passing null
                            try { mi.Invoke(inter, new object[] { null }); didInvoke = true; }
                            catch { }
                        }
                    }

                    if (didInvoke) break;
                }
                catch
                {
                    // Ignore a single call failure and continue trying the next method
                }
            }

            
            try
            {
                
                var fields = interType.GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
                foreach (var f in fields)
                {
                    try
                    {
                        object val = f.GetValue(inter);
                        if (val == null) continue;

                        
                        if (val is UnityEngine.Object uoVal)
                        {
                            if (IsObjectBelongsToTarget(uoVal, targetRoot))
                            {
                                
                                try { f.SetValue(inter, null); }
                                catch { }
                            }
                        }
                        else if (val is System.Collections.IList listVal)
                        {
                            // If it is a list, try removing all elements pointing to the target
                            bool removedAny = false;
                            for (int i = listVal.Count - 1; i >= 0; --i)
                            {
                                var item = listVal[i];
                                if (item is UnityEngine.Object uoItem && IsObjectBelongsToTarget(uoItem, targetRoot))
                                {
                                    try { listVal.RemoveAt(i); removedAny = true; } catch { }
                                }
                            }
                            if (removedAny) { /* ok */ }
                        }
                    }
                    catch { }
                }

                // Clean up writable attributes
                var props = interType.GetProperties(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
                foreach (var p in props)
                {
                    if (!p.CanRead) continue;
                    object val;
                    try { val = p.GetValue(inter); } catch { continue; }
                    if (val == null) continue;

                    if (p.CanWrite && val is UnityEngine.Object uoVal)
                    {
                        if (IsObjectBelongsToTarget(uoVal, targetRoot))
                        {
                            try { p.SetValue(inter, null); } catch { }
                        }
                    }
                    else if (val is System.Collections.IList listVal)
                    {
                        for (int i = listVal.Count - 1; i >= 0; --i)
                        {
                            var item = listVal[i];
                            if (item is UnityEngine.Object uoItem && IsObjectBelongsToTarget(uoItem, targetRoot))
                            {
                                try { listVal.RemoveAt(i); } catch { }
                            }
                        }
                    }
                }
            }
            catch
            {
                // Ignore the exceptions that reflections may throw
            }
        } // end foreach interactor
    }


    private bool IsObjectBelongsToTarget(UnityEngine.Object obj, GameObject targetRoot)
    {
        if (obj == null || targetRoot == null) return false;

        if (obj == (UnityEngine.Object)targetRoot) return true;

        var comp = obj as Component;
        if (comp != null)
        {
            return comp.gameObject == targetRoot || comp.transform.IsChildOf(targetRoot.transform);
        }

        var t = obj as Transform;
        if (t != null)
        {
            return t.gameObject == targetRoot || t.IsChildOf(targetRoot.transform);
        }

        return false;
    }
}

// End code snippet.