using UnityEngine;

/*
Codes below are generated by ChatGPT, this switch between uniform and non-uniform scaling.
https://chatgpt.com
The code snippet appears in its original form.
*/


public class NonUniformScaler : MonoBehaviour
{
    [Header("Scaling Mode Settings")]
    public bool isUniform = true;  // Uniform by default

    [Header("Linked Indicators")]
    public ScalingModeIndicator indicator;   // Hover notice

    private Vector3 initialScale;

    void Start()
    {
        initialScale = transform.localScale;

        // Uniform by default
        if (indicator != null)
            indicator.SetUniformMode(isUniform);
    }

    void Update()
    {
        // Detects 'B' on right controller
        if (OVRInput.GetDown(OVRInput.Button.Two, OVRInput.Controller.RTouch))
        {
            ToggleScalingMode();
        }

        // Scaling sample
        if (Input.GetKey(KeyCode.UpArrow))
        {
            if (isUniform)
                transform.localScale += Vector3.one * Time.deltaTime;
            else
                transform.localScale += new Vector3(Time.deltaTime, 0, 0);
        }

        if (Input.GetKey(KeyCode.DownArrow))
        {
            if (isUniform)
                transform.localScale -= Vector3.one * Time.deltaTime;
            else
                transform.localScale -= new Vector3(Time.deltaTime, 0, 0);
        }
    }

    private void ToggleScalingMode()
    {
        isUniform = !isUniform;

        if (indicator != null)
            indicator.SetUniformMode(isUniform);
    }
}

// End code snippet