using UnityEngine;
using TMPro;

/*
Codes below are generated by ChatGPT, this is the scaling manage that allows hover indicators and button switching.
https://chatgpt.com
The code snippet appears in its original form.
*/


public class ScalingModeIndicator : MonoBehaviour
{
    [Header("XR Controller Reference")]
    public Transform rightController;
    public Vector3 offset = new Vector3(0, 0.1f, 0);

    [Header("Display Text")]
    public string uniformText = "U";
    public string nonUniformText = "NU";

    [Header("Text Appearance")] // Newly added attribute
    public Color textColor = Color.white;
    public float fontSize = 0.25f;

    private TextMeshPro floatingText;
    private bool isUniform = true;

    void Start()
    {
        GameObject textObj = new GameObject("ScalingModeFloatingText");
        floatingText = textObj.AddComponent<TextMeshPro>();
        floatingText.fontSize = fontSize;       // Setting on panel
        floatingText.alignment = TextAlignmentOptions.Center;
        floatingText.color = textColor;        // Setting on panel
        floatingText.text = uniformText;
    }

    void Update()
    {
        if (rightController)
        {
            floatingText.transform.position = rightController.position + rightController.TransformVector(offset);
            floatingText.transform.rotation = Quaternion.LookRotation(
                floatingText.transform.position - Camera.main.transform.position);
        }
    }

    public void SetUniformMode(bool uniform)
    {
        isUniform = uniform;
        floatingText.text = isUniform ? uniformText : nonUniformText;
    }

    public bool IsUniformMode()
    {
        return isUniform;
    }
}

// End code snippet