using UnityEngine;

/*
Codes below are generated by ChatGPT, this is the tutorial manager, aims to control the sequence for texts to appear and disappear
after certain actions.
https://chatgpt.com
The code snippet appears in its original form.
*/


public class TutorialManager : MonoBehaviour
{
    [Header("Tutorial Objects")]
    public GameObject text1;
    public GameObject text2;
    public GameObject portal;

    [Header("Grab Shape Reference")]
    public CloneOnGrab grabShape; // Bound to the shape with grabbable

    private bool hasTriggered = false;

    private void Start()
    {
        // Initial status
        if (text1 != null) text1.SetActive(true);
        if (text2 != null) text2.SetActive(false);
        if (portal != null) portal.SetActive(false);

        // Register 'clone on grab' event
        if (grabShape != null)
        {
            grabShape.OnCloneSpawned += OnGrabShapeActivated;
        }
        else
        {
            Debug.LogError("[TutorialManager] grabShape is empty！");
        }
    }

    private void OnDestroy()
    {
        if (grabShape != null)
        {
            grabShape.OnCloneSpawned -= OnGrabShapeActivated;
        }
    }

    // Perform when CloneOnGrab generate clone shape
    private void OnGrabShapeActivated(GameObject clone)
    {
        if (hasTriggered) return;
        hasTriggered = true;

        if (text1 != null) text1.SetActive(false);
        if (text2 != null) text2.SetActive(true);
        if (portal != null) portal.SetActive(true);
    }
}

// End of the code