using UnityEngine;

/*
Codes below are generated by ChatGPT, this is the tutorial manager, aims to control the sequence for texts to appear and disappear
after certain actions.
https://chatgpt.com
The code snippet appears in its original form.
*/


public class TutorialFlowManager : MonoBehaviour
{
    [Header("Scaling Mode Manager Reference")]
    public ScalingModeIndicator scalingIndicator;

    [Header("Tutorial UI Objects")]
    public GameObject text1;
    public GameObject text2;
    public GameObject text3;
    public GameObject portal;

    private bool lastModeIsUniform = true;

    void Start()
    {
        if (scalingIndicator == null)
        {
            Debug.LogError("[TutorialFlowManager] ScalingModeIndicator is empty！");
            enabled = false;
            return;
        }

        UpdateTutorialState(scalingIndicator.IsUniformMode());
    }

    void Update()
    {
        bool currentMode = scalingIndicator.IsUniformMode();

        if (currentMode != lastModeIsUniform)
        {
            UpdateTutorialState(currentMode);
            lastModeIsUniform = currentMode;
        }
    }

    private void UpdateTutorialState(bool isUniform)
    {
        if (isUniform)
        {
            // Uniform mode
            SetActiveSafe(text1, true);
            SetActiveSafe(text2, true);
            SetActiveSafe(text3, false);
            SetActiveSafe(portal, false);
        }
        else
        {
            // Non-uniform mode
            SetActiveSafe(text1, false);
            SetActiveSafe(text2, false);
            SetActiveSafe(text3, true);
            SetActiveSafe(portal, true);
        }

    }

    private void SetActiveSafe(GameObject obj, bool active)
    {
        if (obj != null)
        {
            obj.SetActive(active);
        }
    }
}

// End of the code