using System.Collections.Generic;
using UnityEngine;
using TMPro;

/*
Codes below are generated by ChatGPT, this code switch clone shapes isKinematic option to allow simple gravity control.
https://chatgpt.com
The code snippet appears in its original form.
*/


public class CloneKinematicToggle : MonoBehaviour
{
    [Header("XR Controller Reference")]
    public Transform leftController;
    public Vector3 indicatorOffset = new Vector3(0, 0.1f, 0);

    [Header("Clone Tag")]
    public string cloneTag = "Clone";

    [Header("Indicator Settings")]
    public string kinematicText = "K"; // Hovering
    public string dynamicText = "D";   // With gravity
    public Color textColor = Color.white;
    public float fontSize = 0.25f;

    private bool isKinematic = false;
    private TextMeshPro indicatorText;

    void Start()
    {
        // Create hover indicator
        GameObject textObj = new GameObject("KinematicIndicator");
        indicatorText = textObj.AddComponent<TextMeshPro>();
        indicatorText.fontSize = fontSize;
        indicatorText.alignment = TextAlignmentOptions.Center;
        indicatorText.color = textColor;
        indicatorText.text = isKinematic ? kinematicText : dynamicText;
    }

    void Update()
    {
        // Follows right controller
        if (leftController && indicatorText != null)
        {
            indicatorText.transform.position = leftController.position + leftController.TransformVector(indicatorOffset);
            indicatorText.transform.rotation = Quaternion.LookRotation(
                indicatorText.transform.position - Camera.main.transform.position);
        }

        // Detects the press of 'Y'
        if (OVRInput.GetDown(OVRInput.Button.Four)) // Button.Three = Y
        {
            ToggleKinematic();
        }
    }

    private void ToggleKinematic()
    {
        isKinematic = !isKinematic;

        // Update hover character
        if (indicatorText != null)
            indicatorText.text = isKinematic ? kinematicText : dynamicText;

        // Iterate through all the clone object.
        GameObject[] clones = GameObject.FindGameObjectsWithTag(cloneTag);
        foreach (GameObject clone in clones)
        {
            Rigidbody rb = clone.GetComponent<Rigidbody>();
            if (rb != null)
            {
                rb.isKinematic = isKinematic;
            }
        }
    }
}
