using UnityEngine;
using System;

/*
Codes below are generated by ChatGPT, it allows highlighting with certain interaction.
https://chatgpt.com
The code snippet appears in its original form
*/


public class ClonePhysicsController : MonoBehaviour
{
    [Tooltip("Material for Highlight")]
    public Material highlightMaterial;

    private Material originalMaterial;
    private Renderer rend;
    private bool isHighlighted = false;

    // Static event, tells every clone object to follow
    public static event Action<bool> OnHighlightStateChanged;

    private void Awake()
    {
        rend = GetComponent<Renderer>();
        if (rend != null)
        {
            originalMaterial = rend.material;
        }
    }

    // tied to PokeInteractable's 'WhenSelect' attribute
    public void ToggleHighlight()
    {
        isHighlighted = !isHighlighted;

        if (rend != null)
        {
            rend.material = isHighlighted ? highlightMaterial : originalMaterial;
        }

        // spread to all clone objects
        OnHighlightStateChanged?.Invoke(isHighlighted);
    }
}

// End code snippet (Enables highlight when triggered.)